Repository pagopa/pagopa-api-config-starter, pull requests merged in 2023-04, with the labels that each got.

#13 Pagopa 834 starter library update
  src/main/java/it/gov/pagopa/apiconfig/starter/entity/CanaleTipoVersamento.java
  src/main/java/it/gov/pagopa/apiconfig/starter/entity/Canali.java
  src/main/java/it/gov/pagopa/apiconfig/starter/entity/CanaliNodo.java
  src/main/java/it/gov/pagopa/apiconfig/starter/entity/CanaliView.java
  src/main/java/it/gov/pagopa/apiconfig/starter/entity/CdiDetail.java
  src/main/java/it/gov/pagopa/apiconfig/starter/entity/CdiFasciaCostoServizio.java
  src/main/java/it/gov/pagopa/apiconfig/starter/entity/CdiInformazioniServizio.java
  src/main/java/it/gov/pagopa/apiconfig/starter/entity/CdiMaster.java
  src/main/java/it/gov/pagopa/apiconfig/starter/entity/CdiMasterValid.java
  src/main/java/it/gov/pagopa/apiconfig/starter/entity/CodifichePa.java
  src/main/java/it/gov/pagopa/apiconfig/starter/entity/ConfigurationKeys.java
  src/main/java/it/gov/pagopa/apiconfig/starter/entity/ConfigurationKeysView.java
  src/main/java/it/gov/pagopa/apiconfig/starter/entity/ElencoServizi.java
  src/main/java/it/gov/pagopa/apiconfig/starter/entity/FtpServers.java
  src/main/java/it/gov/pagopa/apiconfig/starter/entity/GdeConfigPk.java
  src/main/java/it/gov/pagopa/apiconfig/starter/entity/IbanValidiPerPa.java
  src/main/java/it/gov/pagopa/apiconfig/starter/entity/InformativeContoAccreditoDetail.java
  src/main/java/it/gov/pagopa/apiconfig/starter/entity/InformativeContoAccreditoMaster.java
  src/main/java/it/gov/pagopa/apiconfig/starter/entity/InformativePaDetail.java
  src/main/java/it/gov/pagopa/apiconfig/starter/entity/InformativePaFasce.java
  src/main/java/it/gov/pagopa/apiconfig/starter/entity/InformativePaMaster.java
  src/main/java/it/gov/pagopa/apiconfig/starter/entity/IntermediariPa.java
  src/main/java/it/gov/pagopa/apiconfig/starter/entity/IntermediariPsp.java
  src/main/java/it/gov/pagopa/apiconfig/starter/entity/Pa.java
  src/main/java/it/gov/pagopa/apiconfig/starter/entity/PaStazionePa.java
  src/main/java/it/gov/pagopa/apiconfig/starter/entity/Pdd.java
  src/main/java/it/gov/pagopa/apiconfig/starter/entity/Psp.java
  src/main/java/it/gov/pagopa/apiconfig/starter/entity/PspCanaleTipoVersamento.java
  src/main/java/it/gov/pagopa/apiconfig/starter/entity/PspCanaleTipoVersamentoCanale.java
  src/main/java/it/gov/pagopa/apiconfig/starter/entity/ServiceAmountCosmos.java
  src/main/java/it/gov/pagopa/apiconfig/starter/entity/Stazioni.java
  src/main/java/it/gov/pagopa/apiconfig/starter/entity/TipiVersamento.java
  src/main/java/it/gov/pagopa/apiconfig/starter/entity/WfespPluginConf.java
  src/main/java/it/gov/pagopa/apiconfig/starter/repository/CacheRepository.java
  src/main/java/it/gov/pagopa/apiconfig/starter/repository/CanaleTipoVersamentoRepository.java
  src/main/java/it/gov/pagopa/apiconfig/starter/repository/CanaliRepository.java
  src/main/java/it/gov/pagopa/apiconfig/starter/repository/CdiMasterRepository.java
  src/main/java/it/gov/pagopa/apiconfig/starter/repository/CdiMasterValidRepository.java
  src/main/java/it/gov/pagopa/apiconfig/starter/repository/CodifichePaRepository.java
  src/main/java/it/gov/pagopa/apiconfig/starter/repository/HealthCheckRepository.java
  src/main/java/it/gov/pagopa/apiconfig/starter/repository/IbanValidiPerPaRepository.java
  src/main/java/it/gov/pagopa/apiconfig/starter/repository/InformativeContoAccreditoMasterRepository.java
  src/main/java/it/gov/pagopa/apiconfig/starter/repository/InformativePaMasterRepository.java
  src/main/java/it/gov/pagopa/apiconfig/starter/repository/PaRepository.java
  src/main/java/it/gov/pagopa/apiconfig/starter/repository/PaStazionePaRepository.java
  src/main/java/it/gov/pagopa/apiconfig/starter/repository/PspRepository.java
  src/main/java/it/gov/pagopa/apiconfig/starter/repository/StazioniRepository.java
Labels: enhancement, minor, size/large

#15 PAGOPA-834-fix: fix
  pom.xml
  src/main/java/it/gov/pagopa/apiconfig/starter/entity/BinaryFile.java
  src/main/java/it/gov/pagopa/apiconfig/starter/entity/CanaleTipoVersamento.java
  src/main/java/it/gov/pagopa/apiconfig/starter/entity/Canali.java
  src/main/java/it/gov/pagopa/apiconfig/starter/entity/CanaliNodo.java
  src/main/java/it/gov/pagopa/apiconfig/starter/entity/CdiDetail.java
  src/main/java/it/gov/pagopa/apiconfig/starter/entity/CdiPreference.java
  src/main/java/it/gov/pagopa/apiconfig/starter/entity/CdsSoggettoServizio.java
  src/main/java/it/gov/pagopa/apiconfig/starter/entity/CodifichePa.java
  src/main/java/it/gov/pagopa/apiconfig/starter/entity/ConfigurationKeys.java
  src/main/java/it/gov/pagopa/apiconfig/starter/entity/ConfigurationKeysView.java
  src/main/java/it/gov/pagopa/apiconfig/starter/entity/IbanValidiPerPa.java
  src/main/java/it/gov/pagopa/apiconfig/starter/entity/InformativePaDetail.java
  src/main/java/it/gov/pagopa/apiconfig/starter/entity/IntermediariPa.java
  src/main/java/it/gov/pagopa/apiconfig/starter/entity/Pa.java
  src/main/java/it/gov/pagopa/apiconfig/starter/entity/PaStazionePa.java
  src/main/java/it/gov/pagopa/apiconfig/starter/entity/Stazioni.java
  src/main/java/it/gov/pagopa/apiconfig/starter/repository/CdiMasterValidRepository.java
  src/main/java/it/gov/pagopa/apiconfig/starter/repository/CdsSoggettoServizioRepository.java
  src/main/java/it/gov/pagopa/apiconfig/starter/repository/CodifichePaRepository.java
  src/main/java/it/gov/pagopa/apiconfig/starter/repository/HealthCheckRepository.java
  src/main/java/it/gov/pagopa/apiconfig/starter/repository/IbanValidiPerPaRepository.java
  src/main/java/it/gov/pagopa/apiconfig/starter/repository/PaStazionePaRepository.java
  src/main/java/it/gov/pagopa/apiconfig/starter/repository/PspCanaleTipoVersamentoRepository.java
  src/main/java/it/gov/pagopa/apiconfig/starter/repository/StazioniRepository.java
  src/main/java/it/gov/pagopa/apiconfig/starter/util/NumericBooleanConverter.java
  src/main/java/it/gov/pagopa/apiconfig/starter/util/YesNoConverter.java
Labels: bug, minor, size/small

#17 feat: Added fetch pa to CODIFICHE_PA query
  src/main/java/it/gov/pagopa/apiconfig/starter/repository/CodifichePaRepository.java
Labels: bug, patch, size/small
