Repository pagopa/pagopa-api-config-starter, pull requests merged in 2023-07, with the labels that each got.

#30 [PAGOPA-1012] feat: added queries for search by broker description
  src/main/java/it/gov/pagopa/apiconfig/starter/repository/StazioniRepository.java
Labels: enhancement, minor, size/small

#31 [PAGOPA-668] fix: set CanaliRepository usable with JPA Specification
  src/main/java/it/gov/pagopa/apiconfig/starter/repository/CanaliRepository.java
Labels: enhancement, minor, size/small

#32 removed duplication
  pom.xml
  src/main/java/it/gov/pagopa/apiconfig/starter/entity/CdiDetail.java
  src/main/java/it/gov/pagopa/apiconfig/starter/repository/CanaliRepository.java
Labels: patch, size/small

#33 [PAGOPA-1076] Deleting unused NEW_PASSWORD field
  src/main/java/it/gov/pagopa/apiconfig/starter/entity/Canali.java
  src/main/java/it/gov/pagopa/apiconfig/starter/entity/Stazioni.java
Labels: bug, patch, size/small
