Repository pagopa/pagopa-api-config-starter, pull requests merged in 2023-06, with the labels that each got.

#21 [PAGOPA-896] Interfaces for IBAN CRUD new APIs
  src/main/java/it/gov/pagopa/apiconfig/starter/entity/Iban.java
  src/main/java/it/gov/pagopa/apiconfig/starter/entity/IbanAttribute.java
  src/main/java/it/gov/pagopa/apiconfig/starter/entity/IbanAttributeMaster.java
  src/main/java/it/gov/pagopa/apiconfig/starter/entity/IbanMaster.java
  src/main/java/it/gov/pagopa/apiconfig/starter/entity/IcaBinaryFile.java
  src/main/java/it/gov/pagopa/apiconfig/starter/entity/Pa.java
  src/main/java/it/gov/pagopa/apiconfig/starter/repository/IbanAttributeMasterRepository.java
  src/main/java/it/gov/pagopa/apiconfig/starter/repository/IbanAttributeRepository.java
  src/main/java/it/gov/pagopa/apiconfig/starter/repository/IbanMasterRepository.java
  src/main/java/it/gov/pagopa/apiconfig/starter/repository/IbanRepository.java
  src/main/java/it/gov/pagopa/apiconfig/starter/repository/IcaBinaryFileRepository.java
Labels: enhancement, minor

#23 Pagopa 1011 creazione function per lettura e aggiornamento file xml
  src/main/java/it/gov/pagopa/apiconfig/starter/entity/IbanMaster.java
  src/main/java/it/gov/pagopa/apiconfig/starter/entity/IcaBinaryFile.java
  src/main/java/it/gov/pagopa/apiconfig/starter/repository/IbanRepository.java
  src/main/java/it/gov/pagopa/apiconfig/starter/repository/IcaBinaryFileRepository.java
  src/main/java/it/gov/pagopa/apiconfig/starter/repository/PaRepository.java
Labels: enhancement, minor, size/small

#24 update starter version
  pom.xml
Labels: bug, patch, size/small

#25 Update pom.xml
  pom.xml
Labels: bug, patch, size/small

#26 Pagopa 1035 tables adjustment
  .gitignore
  src/main/java/it/gov/pagopa/apiconfig/starter/entity/IcaBinaryFile.java
Labels: enhancement, minor, size/small
