Repository pagopa/pagopa-api-config-starter, pull requests merged in 2023-05, with the labels that each got.

#18 [PAG-2552] FLAG_PSP_CP
  src/main/java/it/gov/pagopa/apiconfig/starter/entity/CanaliNodo.java
  src/main/java/it/gov/pagopa/apiconfig/starter/entity/CanaliView.java
Labels: minor, size/small

#19 [PAGOPA-930] Retrieve stations by broker
  src/main/java/it/gov/pagopa/apiconfig/starter/repository/StazioniRepository.java
Labels: enhancement, size/small

#20 fix: resolved typo on queries
  src/main/java/it/gov/pagopa/apiconfig/starter/repository/StazioniRepository.java
Labels: bug, patch, size/small
