Repository pagopa/pagopa-api-config-starter, pull requests merged in 2024-07, with the labels that each got.

#48 [VAS-1170] feat: Add station maintenance entity
  src/main/java/it/gov/pagopa/apiconfig/starter/entity/StationMaintenance.java
  src/main/java/it/gov/pagopa/apiconfig/starter/entity/StationMaintenanceExpandedView.java
  src/main/java/it/gov/pagopa/apiconfig/starter/entity/StationMaintenanceSummaryId.java
  src/main/java/it/gov/pagopa/apiconfig/starter/entity/StationMaintenanceSummaryView.java
  src/main/java/it/gov/pagopa/apiconfig/starter/repository/StationMaintenanceExpandedViewRepository.java
  src/main/java/it/gov/pagopa/apiconfig/starter/repository/StationMaintenanceRepository.java
  src/main/java/it/gov/pagopa/apiconfig/starter/repository/StationMaintenanceSummaryViewRepository.java
Labels: enhancement, minor

#49 [PAGOPA-1732] chore: introduced aca and standin flags to PaStazionePa
  src/main/java/it/gov/pagopa/apiconfig/starter/entity/PaStazionePa.java
  src/main/java/it/gov/pagopa/apiconfig/starter/repository/StationMaintenanceRepository.java
Labels: enhancement, patch, size/small

#50 fix: StationMaintenanceRepository paged find casting on null date time
  src/main/java/it/gov/pagopa/apiconfig/starter/repository/StationMaintenanceRepository.java
Labels: patch, size/small

#51 fix: updated flag converters for aca and standIn.
  src/main/java/it/gov/pagopa/apiconfig/starter/entity/PaStazionePa.java
  src/main/java/it/gov/pagopa/apiconfig/starter/entity/StationMaintenance.java
  src/main/java/it/gov/pagopa/apiconfig/starter/util/DummyBooleanConverter.java
Labels: minor, size/small
